function(set_warning_level project_name)
  if(MSVC)
	  target_compile_options(${project_name} PRIVATE /W4)
  else()
    target_compile_options(${project_name} PRIVATE -Wall -Wextra -pedantic)
  endif()
endfunction()
