DROP OWNED BY test_user CASCADE;
DROP USER IF EXISTS test_user;
DROP DATABASE IF EXISTS test_db;
CREATE DATABASE test_db;

CREATE USER test_user WITH ENCRYPTED PASSWORD 'aaa';
GRANT ALL PRIVILEGES ON DATABASE test_db TO test_user;
